server.port: 8045
microservice.contextPath: '/api/v1/myRetail'

spring:
  application:
    name: my-retail-service  # Service registers under this name
  mvc:
    dispatch-trace-request: true
  data:
    cassandra: # Cassandra properties
      contact-points: localhost
      port          : 9042
      keyspace-name : my_retail
      username      : cassandra
      password      : cassandra
      ssl           : false
      consistency-level: LOCAL_QUORUM


product:
  rest:
    totalconnections: 10
    readtimeout: 3000
    connectionTimeout: 4000
  getProductsUrl: https://redsky.target.com/v2/pdp/tcin/13860428?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics
